#pragma once

void default_constants();

void drive_example();
void turn_example();
void drive_and_turn();
void wait_until_change_speed();
void swing_example();
void motion_chaining();
void combining_movements();
void interfered_example();
void odom_drive_example();
void odom_pure_pursuit_example();
void odom_pure_pursuit_wait_until_example();
void odom_boomerang_example();
void odom_boomerang_injected_pure_pursuit_example();
void measure_offsets();
void TestAuton(); 
void SpooktacularAutonRight(); 
void SpooktacularAutonLeft();
void AutonRightMatchloaderOnly();
void AutonLeftMatchloaderOnly();
void SpooktacularAuton60Seconds();
void SpaceAuton60Seconds();
void PressureBreakpointSkills();
void SuperSoloAWP();
void MoveFwd1();
 void Move_Nothing_Auton();
 void Right_7_ball();
 void Left_7_ball();
void SplitGoalRight();
